### ISSUE TITLE
After clone and run yarn to install dependencies got http://localhost:undefined

### ISSUE THREAD

**Issue by mauricionr** [marko-js-samples/marko-starter-demo#1]
I've tried to install the dependencies with yarn

![image](https://cloud.githubusercontent.com/assets/2263551/23262132/57ef5bcc-f9b8-11e6-9801-6188ef7956e4.png)

After npm install could run in a port like 8080

**Comment by austinkelleher** [comment]
This should be fixed now. Thanks for reporting the issue.
